### ISSUE TITLE
wolfSSH_set_fd: portability issue with sockets on win64

### ISSUE THREAD

**Issue by bagder** [wolfSSL/wolfssh#157]
The `wolfSSH_set_fd()` function takes an 'int' for socket, which won't work with win64 that uses a `SOCKET` type which is 64 bit while int is 32 bit:

https://github.com/wolfSSL/wolfssh/blob/57a869ecf908cb041c02d5dbc7d9178a41d813cd/wolfssh/ssh.h#L67

Update: the same problem exists for `wolfSSH_get_fd()`

**Comment by ejohnstown** [comment]
And I'm running into a raft of problems with Micrium as it doesn't use file descriptors, it is all pointers to struct FS_FILE. I'll get that updated.

**Comment by ejohnstown** [comment]
This should be fixed with pull request #162.
