### ISSUE TITLE
wolfssh/wolfsftp.h is not C90 compliant

### ISSUE THREAD

**Issue by bagder** [wolfSSL/wolfssh#158]
I've started working on using wolfSSH as a backend for curl, and in curl we are strictly on C89/C90 and usually use compiler options that scream loudly when we're not. When doing this, we get this warning below in a wolfssh header.

(wolfssh from git as of just minutes ago)

I realize you might not care about C90 compliance, but then again you may.

~~~
.../include/wolfssh/wolfsftp.h:103:31: warning: ISO C restricts enumerator values to range of ‘int’ [-Wpedantic]
     WOLFSSH_FILEATRB_EXT    = 0x80000000
                               ^~~~~~~~~~

**Comment by JacobBarthelmeh** [comment]
Thanks for the report on this Daniel, closing with the fix from PR#161 having been merged.
