### ISSUE TITLE
Possible copy/paste error in wolfsftp.c

### ISSUE THREAD

**Issue by LinuxJedi** [wolfSSL/wolfssh#179]
In wolfsftp.c function wolfSSH_SFTP_Remove() this repeated condition is used four times:

`if (ssh->error != WS_WANT_READ && ssh->error != WS_WANT_READ)`

I presume the condition should be WS_WANT_WRITE but didn't want to submit a patch until I was sure that was the intention.

(also found using cppcheck)

**Comment by JacobBarthelmeh** [comment]
Hi LinuxJedi, That is correct it should have a check for WS_WANT_READ && WS_WANT_WRITE not the double check on WS_WANT_READ that it currently has.

**Comment by LinuxJedi** [comment]
Cool, want me to patch it or have you got it?

**Comment by JacobBarthelmeh** [comment]
I'll go ahead and add in a pull request for it and make reference to this issue number as the initial report. Thanks again LinuxJedi for the feedback!

**Comment by LinuxJedi** [comment]
No problem. Glad I could help :)
