### ISSUE TITLE
WS_SFTP_FILEATRB->sz is undocumented?

### ISSUE THREAD

**Issue by bagder** [wolfSSL/wolfssh#185]
Checking the size of a remote file with `wolfSSH_SFTP_STAT` gets me back the result in a `WS_SFTP_FILEATRB` struct.

It has a struct field named 'word32 sz[2]` that I presume is the size of the file. Given that the file size is 64 bits in total (I hope), which array index is the high and the low 32 bits here? Can I suggest adding this in a documentation or as a clear comment in the header file next to the struct declaration ?

https://github.com/wolfSSL/wolfssh/blob/f8c7076d596cc708e5ef9ee5582ce7b4199e48b6/wolfssh/wolfsftp.h#L128

**Comment by JacobBarthelmeh** [comment]
adding a comment in the code near it

sz[0] being the lower and sz[1] being the upper
