### ISSUE TITLE
The wolfSSH_SFTP_SendReadPacket documentation is out of sync

### ISSUE THREAD

**Issue by bagder** [wolfSSL/wolfssh#187]
It is documented here: https://www.wolfssl.com/docs/wolfssh-manual/#h.ew6stinnse5x

But the header file says the forth argument is a `const word32* ofst`. It would be neat if the documentation would explain this.

**Comment by bagder** [comment]
Also: shouldn't the offset be 64 bits? What if the file is larger than 4GB?

**Comment by JacobBarthelmeh** [comment]
Initially was a word64 type. It got changed to a word32 array to be more portable but the documents did not get changed to reflect that. I'll work on updating it.

word32 ofst[0] is lower
word32 ofst[1] is upper
