### ISSUE TITLE
How to build wolfSSH on STM32F767?

### ISSUE THREAD

**Issue by 1838039453** [wolfSSL/wolfssh#219]

**Comment by kaleb-himes** [comment]
Hi @1838039453,

Simply pull in wolfSSL's wolfCrypt crypto files (https://github.com/wolfSSL/wolfssl/tree/master/wolfcrypt/src), use the setting ```WOLFCRYPT_ONLY``` to turn off any TLS dependencies then pull in the wolfSSH sources also to start working with wolfSSH in an STM project.

Warm Regards,
