### ISSUE TITLE
Does the SFTP server support IPV6？

### ISSUE THREAD

**Issue by liandaming** [wolfSSL/wolfssh#524]
I would like to know if the SFTP server in Wolfssh supports IPV6. If you could tell me, I would be very grateful

**Comment by anhu** [comment]
Hi @liandaming , 

My name is Anthony and I am a member of the wolfSSL team. 

In general, wolfSSH has IPv6 support.  That will work for both servers and clients. Have you tried?  Do your results indicate an IPv6 failure?  

Warm regards, Anthony

**Comment by ejohnstown** [comment]
wolfSSH doesn't support IPv6 specifically. Sockets and addressing are left to the application using wolfSSH. That being said, the wolfSSHd server isn't listening to ::1. There's no reason for it not to, it just doesn't right now.
