### ISSUE TITLE
Rekeying doesn't work in certain cases

### ISSUE THREAD

**Issue by falemagn** [wolfSSL/wolfssh#605]
The following command causes the SFTP session to bail out with the error **`WS_OVERFLOW_E`**:
```
sftp -o RekeyLimit=100 user@localhost
```

Assuming `user` is a real user on the sftp server, which is listening on `localhost` at the standard port.

My tests have shown that the issue doesn't manifest itself with the `echoserver`, however we've implemented a slightly different worker loop than the one being used by the echoserver, and that might be the trigger reason.

Our analysis identified the problem to be here: https://github.com/wolfSSL/wolfssh/blob/74cf1d4014c81e2ba21974a45312e2831a7d9aba/src/internal.c#L7847

Simply OR-ing `ret == WS_WANT_READ` on that line seems to fix the issue.

**Comment by ejohnstown** [comment]
I wasn't able to recreate this issue. But, I'm going to merge your fix. That value should have been there.
