### ISSUE TITLE
Failed to connect to wolfssh server with kex ID_ECDH_SHA2_NISTP*

### ISSUE THREAD

**Issue by oleg35hp** [wolfSSL/wolfssh#678]
internal.c, SendKexDhReply:

Flags useEcc, useEccKyber and useCurve25519 are mutual exclusive, and missed 'else if' at line 10219 leads to error code WS_ERROR at line 10413.

**Comment by ejohnstown** [comment]
I'm taking a look at this. I see a few inconsistencies in the code. Thanks for the feedback.
