### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by mintty** [wolfSSL/wolfssh#745]
configure.ac:15: installing 'build-aux/missing'
Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
...
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1

**Comment by anhu** [comment]
Hi @mintty , 

My name is Anthony and I am a member of the wolfSSL team. PLease note that you'll need to install the libtool package as our build process requires it. As an example, on Ubuntu, you would issue the following command: 

```
sudo apt install libtool
```

Hope this helps!!

Warm regards, Anthony
