### ISSUE TITLE
How can I build this project for arch arm?

### ISSUE THREAD

**Issue by pangpangshui** [wolfSSL/wolfssh#89]
I built wolfssl when I excute "make check" but it gave me this error log:

```./testsuite/testsuite.test: line 117: /tes    tsuite/.libs/lt-testsuite.test: cannot execute binary file: Exec format erro  ```

My configurition is sudo ./configure CC=arm-linux-gcc --prefix=/home/zjq/Downloads/wolfssl-3.15.3/install --host=arm-linux --enable-ssh
@cconlon

**Comment by JacobBarthelmeh** [comment]
Hi pangpangshui,

For cross compiling do not use sudo, this sets the ownership for the executables and anything built to be sudo user. I would also recommend building a static library and executables if cross compiling. Using "--enable-static --disable-shared" will remove the script wrappers for examples/tests created when using autotools, though that is not required.

The last thing is to make sure that the executable is being ran on the system it was compiled for.

Regards,
Jacob

**Comment by JacobBarthelmeh** [comment]
Hi pangpangshui,

I'm going to go ahead and close this since it's been a couple weeks. You can reach out to us by email (www.wolfssl.com) or resurrect the case here if it's not resolved.

Regards,
Jacob
