### ISSUE TITLE
ssh_client : command not found

### ISSUE THREAD

**Issue by Vaibhav1587** [wolfSSL/wolfssh#94]
> Release : WolfSSH 1.3.0 - stable 

Sorry if I missing something obvious here. But spare me I'm new to this!

I have compiled and build  the code successfully also started the echo server. But when I run the 
`ssh_client localhost -p 22222` 
command in another terminal. I'm getting command not found.

**Comment by ejohnstown** [comment]
"ssh_client" refers to any ssh client. You should be able to use OpenSSH's ssh, PuTTY, etc.

**Comment by ejohnstown** [comment]
And it is a little more complicated than that. Continue to the "testing notes" section. That will describe the sample fake user accounts the echoserver provides. Authentication is environment dependent, and the echoserver provides a fake environment with two users with passwords and two users with public keys.

**Comment by Vaibhav1587** [comment]
Thanks!! 

Starting echoserver and client but nothing going beyond that.. screenshot attached 

Is this the normal behavior ? I was expecting a prompt :| on successful login... 
![wolfssh](https://user-images.githubusercontent.com/34318157/44390156-3fb83580-a54a-11e8-8feb-81c9e198a15d.png)

**Comment by ejohnstown** [comment]
The example server you are running is an echoserver. Anything you type in the client is echoed by the server. The client does not have local echo, so the characters you see have taken a round trip. Note, the end of line received ends up being a CR, without a LF. The local echo ends up writing over itself. The user accounts jack, jill, hansel, and gretel are limited to the echoserver.

wolfSSH implements the SSH protocol as a library to be built into an application. You can use it to talk to the OpenSSH server, and you can use the OpenSSH client, ssh, to talk to the echoserver.

--John

**Comment by Vaibhav1587** [comment]
Great!! Awesome work.

Is there any tutorial or more examples on wolfssh? 
Basically now I need to connect the my server over ssh using public key.

**Comment by ejohnstown** [comment]
The only examples are the ones in the examples directory. The client example's authentication callback function handles collecting the password. You'd have to write your own callback to use an RSA or ECC private key. The echoserver has an example of the server side handling the public keys in its callback. (The authentication callback is required, but it is user application defined.)

**Comment by Vaibhav1587** [comment]
Thanks !!
